
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/snap/cmake/1515/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:13 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/yzhou/.local/bin/"
      - "/home/yzhou/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/home/yzhou/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/home/yzhou/.vscode-server/cli/servers/Stable-ce099c1ed25d9eb3076c11e4a280f3eb52b4fbeb/server/bin/remote-cli/"
      - "/usr/local/cuda/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
    searched_directories:
      - "/home/yzhou/.local/bin/uname"
      - "/home/yzhou/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/home/yzhou/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/home/yzhou/.vscode-server/cli/servers/Stable-ce099c1ed25d9eb3076c11e4a280f3eb52b4fbeb/server/bin/remote-cli/uname"
      - "/usr/local/cuda/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/yzhou/.local/bin"
        - "/home/yzhou/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/yzhou/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli"
        - "/home/yzhou/.vscode-server/cli/servers/Stable-ce099c1ed25d9eb3076c11e4a280f3eb52b4fbeb/server/bin/remote-cli"
        - "/home/yzhou/.local/bin"
        - "/usr/local/cuda/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1515/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:13 (project)"
    message: |
      The system is: Linux - 6.17.0-1012-oem - x86_64
...
