blank_issues_enabled: false
contact_links:
  - name: Modelling / Usage problem
    url: https://github.com/ERGO-Code/HiGHS/discussions
    about: Need help modelling or using HiGHS? Please use Discussions rather than opening an issue.
