# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget libhighs libipx libbasiclu)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target libhighs
add_library(libhighs SHARED IMPORTED)

set_target_properties(libhighs PROPERTIES
  INTERFACE_LINK_LIBRARIES "libipx"
)

# Create imported target libipx
add_library(libipx SHARED IMPORTED)

set_target_properties(libipx PROPERTIES
  INTERFACE_LINK_LIBRARIES "libbasiclu"
)

# Create imported target libbasiclu
add_library(libbasiclu SHARED IMPORTED)

# Import target "libhighs" for configuration "Release"
set_property(TARGET libhighs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libhighs PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mac/projects/HiGHS/brl/lib/libhighs.1.0.0.dylib"
  IMPORTED_SONAME_RELEASE "/Users/mac/projects/HiGHS/brl/lib/libhighs.1.0.dylib"
  )

# Import target "libipx" for configuration "Release"
set_property(TARGET libipx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libipx PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mac/projects/HiGHS/brl/lib/libipx.dylib"
  IMPORTED_SONAME_RELEASE "/Users/mac/projects/HiGHS/brl/lib/libipx.dylib"
  )

# Import target "libbasiclu" for configuration "Release"
set_property(TARGET libbasiclu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libbasiclu PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/mac/projects/HiGHS/brl/lib/libbasiclu.dylib"
  IMPORTED_SONAME_RELEASE "/Users/mac/projects/HiGHS/brl/lib/libbasiclu.dylib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
