# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.0)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS highs::highs highs::cudalin)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target highs::highs
add_library(highs::highs SHARED IMPORTED)

set_target_properties(highs::highs PROPERTIES
  COMPATIBLE_INTERFACE_STRING "HIGHS_MAJOR_VERSION"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-Wno-invalid-offsetof>"
  INTERFACE_HIGHS_MAJOR_VERSION "1"
  INTERFACE_INCLUDE_DIRECTORIES "/include;/home/yzhou/Github/HiGHS;/home/yzhou/Github/HiGHS/highs;/home/yzhou/Github/HiGHS/build_release"
  INTERFACE_POSITION_INDEPENDENT_CODE "ON"
)

# Create imported target highs::cudalin
add_library(highs::cudalin SHARED IMPORTED)

set_target_properties(highs::cudalin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/include;/include;/home/yzhou/Github/HiGHS/highs/pdlp/cupdlp/cuda/../../hipdlp"
  INTERFACE_LINK_LIBRARIES "CUDA::cudart;CUDA::cublas;CUDA::cusparse;m"
)

# Import target "highs::highs" for configuration "Release"
set_property(TARGET highs::highs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(highs::highs PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "highs::cudalin"
  IMPORTED_LOCATION_RELEASE "/home/yzhou/Github/HiGHS/build_release/lib/libhighs.so.1.13.1"
  IMPORTED_SONAME_RELEASE "libhighs.so.1"
  )

# Import target "highs::cudalin" for configuration "Release"
set_property(TARGET highs::cudalin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(highs::cudalin PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/yzhou/Github/HiGHS/build_release/lib/libcudalin.so"
  IMPORTED_SONAME_RELEASE "libcudalin.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
