//
// Created by potekhin on 22.04.2020.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <interfaces/jhi/jni.h>
/* Header for class org_best_team_Highs */

#ifndef _Included_org_best_team_Highs
#define _Included_org_best_team_Highs
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_best_team_Highs
 * Method:    invokeLpOptimization
 * Signature: (III[D[D[D[D[D[I[I[D)V
 */
// Вызов процедуры линейной оптимизации.
JNIEXPORT void JNICALL Java_org_best_team_Highs_invokeLpOptimization
        (JNIEnv *env, jobject thisObj,
         jint numcol,        //!< number of columns
         jint numrow,        //!< number of rows
         jint numnz,       //!< number of entries in the constraint matrix
         jdoubleArray jColcost,   //!< array of length [numcol] with column costs
         jdoubleArray jCollower,  //!< array of length [numcol] with lower column bounds
         jdoubleArray jColupper,  //!< array of length [numcol] with upper column bounds
         jdoubleArray jRowlower,  //!< array of length [numrow] with lower row bounds
         jdoubleArray jRowupper,  //!< array of length [numrow] with upper row bounds
         jintArray jAstart,       //!< array of length [numcol+1] with column start indices
         jintArray jAindex,  //!< array of length [numnz] with row indices of matrix entries
         jdoubleArray jAvalue  //!< array of length [numnz] with value of matrix entries
                );


#ifdef __cplusplus
}
#endif
#endif
