name: proto-win

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install METIS
        run: vcpkg install metis

        # run: ls C:/vcpkg/packages/metis_x64-windows/
        # run: ls C:/vcpkg/packages/metis_x64-windows/lib
        # run: ls C:/vcpkg/packages/metis_x64-windows/share
        # run: ls C:/vcpkg/packages/gklib_x64-windows/share/gklib

      - name: Install OpenBLAS
        run: vcpkg install openblas

      - name: Create build dir
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure cmake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Here is _DIR because with vcpkg CMake find_package works.
        run: |
          cmake $GITHUB_WORKSPACE \
          -DHIPO=ON \
          -Dmetis_DIR=C:/vcpkg/packages/metis_x64-windows/share/metis \
          -DGKlib_DIR=C:/vcpkg/packages/gklib_x64-windows/share/gklib \
          -DOpenBLAS_DIR=C:/vcpkg/packages/openblas_x64-windows/share/openblas

      - name: Build 
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --parallel --config Release

      - name: Test executable 
        working-directory: ${{runner.workspace}}/build
        run: ./Release/bin/highs --solver=hipo $GITHUB_WORKSPACE/check/instances/afiro.mps

      - name: Ctest
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --parallel --timeout 300 --output-on-failure -C Release

  debug:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install METIS
        run: vcpkg install metis

        # run: ls C:/vcpkg/packages/metis_x64-windows/
        # run: ls C:/vcpkg/packages/metis_x64-windows/lib
        # run: ls C:/vcpkg/packages/metis_x64-windows/share
        # run: ls C:/vcpkg/packages/gklib_x64-windows/share/gklib

      - name: Install OpenBLAS
        run: vcpkg install openblas

      - name: Create build dir
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure cmake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Here is _DIR because with vcpkg CMake find_package works.
        run: |
          cmake $GITHUB_WORKSPACE \
          -DHIPO=ON \
          -Dmetis_DIR=C:/vcpkg/packages/metis_x64-windows/share/metis \
          -DGKlib_DIR=C:/vcpkg/packages/gklib_x64-windows/share/gklib \
          -DOpenBLAS_DIR=C:/vcpkg/packages/openblas_x64-windows/share/openblas

      - name: Build 
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --parallel --config Debug

      - name: Test executable 
        working-directory: ${{runner.workspace}}/build
        run: ./Debug/bin/highs --solver=hipo $GITHUB_WORKSPACE/check/instances/afiro.mps

      - name: Ctest
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --parallel --timeout 300 --output-on-failure -C Debug