name: hipo-win

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Debug]
        all_tests: [ON, OFF]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout metis overlay ports
        uses: actions/checkout@v4
        with:
          repository: galabovaa/metis-overlay-ports
          ref: main
          path: overlay-ports

      - name: List overlay contents
        shell: pwsh
        run: Get-ChildItem -Recurse "$env:GITHUB_WORKSPACE/overlay-ports"

      - name: Install metis with overlay port
        shell: pwsh
        run: |
          vcpkg install metis gklib `
          --overlay-ports="$env:GITHUB_WORKSPACE/overlay-ports/metis" `
          --overlay-ports="$env:GITHUB_WORKSPACE/overlay-ports/gklib"

      - name: Install OpenBLAS
        run: vcpkg install openblas[threads]

      - name: Configure CMake 
        run: |
          cmake `
          -S "$env:GITHUB_WORKSPACE/HiGHS" `
          -B "${{ runner.workspace }}/build" `
          -DHIPO=ON `
          -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DALL_TESTS=${{ matrix.all_tests }}

      - name: Build 
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --parallel --config ${{ matrix.config }}

      - name: Test executable 
        working-directory: ${{runner.workspace}}/build
        run: |
          & ".\Release\bin\highs.exe" --solver=hipo `
          "${{ runner.workspace }}/highs-tests/HiGHS/check/instances/afiro.mps"

      - name: Ctest
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --parallel --timeout 300 --output-on-failure -C ${{ matrix.config }}
