name: hpm-linux

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout GKlib
        uses: actions/checkout@v4
        with:
          repository: KarypisLab/GKlib
          ref: master
          path: GKlib

      - name: Checkout METIS
        uses: actions/checkout@v4
        with:
          repository: KarypisLab/METIS
          ref: master
          path: METIS

      - name: Create installs dir
        working-directory: ${{runner.workspace}}
        run: | 
          mkdir installs
          ls

      - name: Install GKLIB
        run: |
          cd GKlib
          make config prefix=${{runner.workspace}}/installs
          make
          make install

      - name: Install METIS
        run: |
          cd METIS
          make config prefix=${{runner.workspace}}/installs
          make
          make install

      - name: Check METIS and GKlib
        working-directory: ${{runner.workspace}}
        run: |
          cd installs
          ls 
          ls lib

      # Use linux default blas for now if available

      # - name: Install OpenBLAS
      #   shell: bash
      #   run: |
      #     sudo apt update
      #     sudo apt install libopenblas-dev 

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake, build and ctest
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DHPM=ON -DMETIS_ROOT=${{runner.workspace}} -DGKLIB_ROOT=${{runner.workspace}}
          cmake --build . --parallel
          ctest --parallel --timeout 300 --output-on-failure

      - name: Test executable
        working-directory: ${{runner.workspace}}/build
        run:  ./bin/highs --solver=hpm $GITHUB_WORKSPACE/check/instances/afiro.mps