name: python-api-windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: highsdev
          create-args: >-
            python==${{matrix.python-version}}
            pytest
            numpy
            pybind11
            cmake
            pkgconfig
            compilers
            openblas
          cache-environment: true
          init-shell: >-
            powershell
            bash

      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Configure CMake
        shell: pwsh
        run: cmake -S . -B build -DFAST_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DHIGHSINT64=on -DCMAKE_INSTALL_PREFIX=C:\Users\runneradmin\micromamba\envs\highsdev

      - name: Build and install
        shell: pwsh
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build build --parallel --config Release
          cmake --install build

      - name: Test Python Interface
        shell: pwsh
        run: |
          pip install -e .
          pytest -v ./highspy/tests/
