name: Python
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            python: 3.11
          - os: ubuntu-latest
            python: 3.11
          - os: windows-2022
            python: 3.12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: python3 -m pip install numpy setuptools wheel pytest
      - run: |
          python3 -m pip install .
          pytest -v
      - run: |
          python3 ./examples/call_highs_from_python_highspy.py
          python3 ./examples/call_highs_from_python_mps.py
          python3 ./examples/call_highs_from_python.py
          python3 ./examples/minimal.py
