# python release WIP
name: test-python-api

on: []
#on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: [3.9]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: highsdev
          create-args: >-
            python==${{ matrix.python }}
            meson
            pkgconfig
            ninja
            zlib
          cache-environment: true
          init-shell: >-
            bash
      - name: Build and test
        shell: bash -l {0}
        run: |
          meson setup bbdir -Duse_zlib=enabled -Dwith_tests=False -Dhighsint64=False -Dwith_pybind11=True --prefix $CONDA_PREFIX
          meson install -C bbdir
      - name: Test Python Interface
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib
          export PYTHONPATH=$PYTHONPATH:$CONDA_PREFIX/usr/local/lib/python${{ matrix.python }}/site-packages
          pip install pytest numpy
          cd ../
          pytest -v ./HiGHS/highspy/tests/
