name: test-nuget-macos

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_macos_intel:
    runs-on: macos-15-intel
    # strategy:
      # matrix:
      #   python: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS
        run: |
         cmake -E make_directory ${{github.workspace}}/build
         cmake -E make_directory ${{github.workspace}}/nugets
         cmake -E make_directory ${{github.workspace}}/test_nuget

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: |
         cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release --parallel

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Dotnet pack
        working-directory: ${{github.workspace}}/build/dotnet/Highs.Native
        run: dotnet pack -c Release /p:Version=1.13.1

      - name: Add local feed
        run: dotnet nuget add source ${{github.workspace}}/nugets

      - name: Dotnet push to local feed
        working-directory: ${{github.workspace}}/build/dotnet/Highs.Native
        run: dotnet nuget push ./bin/Release/*.nupkg -s ${{github.workspace}}/nugets

      - name: Create new project and test
        shell: bash
        working-directory: ${{github.workspace}}/test_nuget
        run: |
          dotnet new console
          rm Program.cs
          cp $GITHUB_WORKSPACE/examples/call_highs_from_csharp.cs .
          dotnet add package Highs.Native -s ${{github.workspace}}/nugets
          dotnet run


  build_macos_arm:
    runs-on: macos-14  # macos-14 is arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS
        run: |
         cmake -E make_directory ${{github.workspace}}/build
         cmake -E make_directory ${{github.workspace}}/nugets
         cmake -E make_directory ${{github.workspace}}/test_nuget

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++


      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release --parallel

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Dotnet pack
        working-directory: ${{github.workspace}}/build/dotnet/Highs.Native
        run: dotnet pack -c Release /p:Version=1.13.1

      - name: Add local feed
        run: dotnet nuget add source ${{github.workspace}}/nugets

      - name: Dotnet push to local feed
        working-directory: ${{github.workspace}}/build/dotnet/Highs.Native
        run: dotnet nuget push ./bin/Release/*.nupkg -s ${{github.workspace}}/nugets

      - name: Create new project and test
        shell: bash
        working-directory: ${{github.workspace}}/test_nuget
        run: |
          dotnet new console
          rm Program.cs
          cp $GITHUB_WORKSPACE/examples/call_highs_from_csharp.cs .
          dotnet add package Highs.Native -s ${{github.workspace}}/nugets
          dotnet run
