name: test-python-api-win

on: []

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: [3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DFAST_BUILD=ON -DBUILD_SHARED_LIBS=ON 

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build . --parallel --config Release
          cmake --install .

        # $Env:HIGHS_LIB_DIR=${{runner.workspace}}/build/highs/lib
        # $Env:Path=$Env:Path+";"+ $Env:HIGHS_LIB_DIR
        # $Env:LIBPATH=$Env:LIBPATH+";"+ $Env:HIGHS_LIB_DIR
        # $Env:PYTHONPATH=$Env:PYTHONPATH+";"+ $Env:HIGHS_LIB_DIR
        # echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HIGHS_LIB_DIR" >> $GITHUB_ENV
        # echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HIGHS_LIB_DIR" >> $GITHUB_ENV

      - name: Install correct python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install pybind11 numpy pyomo pytest 

      - name: Test Python Interface
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          pip install -e ./HiGHS
          pytest -v ./HiGHS/highspy/tests/
