name: test-python-api-mac

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python: [3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Create Install dir
        run: cmake -E make_directory ${{runner.workspace}}/installs

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DFAST_BUILD=ON -DBUILD_SHARED_LIBS=ON 

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build . --parallel 
          export HIGHS_INST_DIR=${{runner.workspace}}/installs
          cmake --install . --prefix $HIGHS_INST_DIR

      - name: Install correct python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install pybind11 numpy pytest

      - name: Test Python Interface
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          HIGHS_LIB_DIR=${{runner.workspace}}/installs/lib
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HIGHS_LIB_DIR
          export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HIGHS_LIB_DIR
          pip install -e ./HiGHS
          pytest -v ./HiGHS/highspy/tests/
